FPS = 30
LEVEL_MAP = {1: [
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ",
    "      k             F                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ",
    "      xxx  c       xxx                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ",
    " F        xxx                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
    "xxx             xx                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ",
    "     xxxx            FFFFFFFFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ",
    "                     FFFFFFFFF                                      F                           xxx                                                                                                                                        c                                                                                                                                     F                                                                                                  F                      c                                                        c                                               F                    ",
    "         xxx         xxx                    c x                      xx                    xxxx                         F                      xxx                                                     c    x                             xxx                                   c                                                            x                              x    x    c                                 F              x                  x                 c         xx                   xx              F            x                c          xxxx             F                 c    F         x                    ",
    "  xx          F   xx          c             xxxx       sx        c               c   Fxxx             F                xx                xxx                  F         c                 F            x               xxx          xx                      x            xx     xxxx                                  c     xx          x                   xx      x    x           xx    F        xx      c F         x        x         x     F   x         x            xxx              xxx     xx                    xxx   xxx         x       x   xxx    xxx            xxx   xx   xx    FFFF   xxx  xx    xx     xx xx     f        ",
    "xxxxx       xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxx   xxxxxxx   xxxxxxxxxxx    xxxxxxxxxxxxx   x      xxx    xxx     xx      xxxx   xxx              xxxx      xxx       xxx     xxxxxxxxxxxx        xx          xxx           xxx                xxxxxxxxxx      xxxxxxx             x   x      x     x      x        xxxx        xx             x   xxx         x                         x   x            xxx   xxx         x                  x                 x                                              xxx                              x                        xxx                 xxxx                               xx      ",

], 2: [

    " xx                                                                                                                                                                                                                                                                                                                                        ",
    " xx                  FFFFFFFFF                        xxxxxxxx              F                           xxx                  x                                                        c           F                   F   xxx                                      c                                                                       ",
    " xx      xxx         xxx                    c xs                     xx                    xxxx                 x         c         F     x        F       xx                         xx          xx   c         FF   xxx                F                     F   xxx      f                                                             ",
    " xxx          F   xx          c             xxxx                 c       x       c   Fxxx          x  F      c      x     xxx       xx    x   x     xxx         F   xx    xx   xx             xx       xx         xx         c       x   xxx         c        xx       xxxxxx                                                              ",
    "             xxx             xxx      xxx                      xxxx   x     x  xxxx            xxxx   x     xxx    xxxx      x      x     x       x            x         x         x              x       xxxx            xxxx    x               xxxx                                                                                    ",
    "                                                    xxx       x                            x       x           x         x        x        x         x       x      x       x           x        x                                                                                                                                        ",
    "                                                         x                          x          x           x          x                x                 x           x         x             x                                                                                                                                            ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                            ",
    "                                                                                                                                                                                                                                                                                                                                           "]}
TILE_SIZE = 64
WIDTH = 1920
HEIGHT = 64 * 13
